name: "Reg"

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: "Bump Version and Publish Package"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref }}
      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Publish Package to npmjs"
        run: |
          npm ci
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
